server:
  port: 8080
  servlet:
    context-path: /jdbc

spring:
  datasource:
    druid:
      username: tester
      password: 1234
      url: jdbc:postgresql://192.168.2.230:15432/test?currentSchema=springboot