server:
  port: 8080
  servlet:
    context-path: /xuyj

springfox:
  documentation:
    auto-startup: true

spring:
  application:
    name: spring-example-swagger
  # 自定义security的用户名和密码
  security:
    user:
      name: jerry
      password: asd