server:
  port: 8080
  servlet:
    context-path: /xuyj

# swagger文档登录信息
swagger:
  username: xuyj
  password: 1234

springfox:
  documentation:
    auto-startup: true

spring:
  application:
    name: spring-example-swagger