server:
  port: 8080
  servlet:
    context-path: /mongo

spring:
  data:
    mongodb:
      host: 192.168.1.221
      port: 17017
      database: distdoc_zb2
      authentication-database: admin
      username: distdoc_zb2
      password: Passw0rd
      buckets: fs
